#!/bin/sh
### BEGIN INIT INFO
# Provides:          launchReact
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable launchReact provided by daemon.
### END INIT INFO

pid_file=/var/run/launchReact.pid
log_file=/usr/local/sbin/api/output.log
case "$1" in

  start)
    touch $pid_file
    touch $log_file
    echo -n " Starting launchReact : "
    exec python /usr/local/sbin/api/api.py > $log_file 2>&1 &
    echo $! > $pid_file
    echo $LANG
    echo " Started [ok] "
    exit 0
    ;;
  stop)
    echo -n " Shutting down launchReact : "
    PID=$(cat $pid_file)
    kill -9 $PID
    echo " Stopped [ok] "
    rm -f $pid_file
    exit 0
    ;;
  status)
    cat $pid_file
    cat $log_file
    exit 0
    ;;
  restart)
    $0 stop
    $0 start
    exit 0
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1

esac
