#!/bin/sh
### BEGIN INIT INFO
# Provides:          launchReact
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable launchReact provided by daemon.
### END INIT INFO

log_file=/usr/local/sbin/api/output.log

case "$1" in

  start)
    touch $log_file
    echo " --- Starting launchReact : "
    exec python /usr/local/sbin/api/api.py > $log_file 2>&1 &
    echo " --- Started [ok] "
    exit 0
    ;;
  stop)
    echo " --- Shutting down launchReact : "
    pidof python | xargs kill -9
    echo " --- Stopped [ok] "
    exit 0
    ;;
  status)
    echo " --- LOG FILE : "
    cat $log_file
    echo " --- END OF LOG FILE"
    exit 0
    ;;
  restart)
    $0 stop
    $0 start
    exit 0
    ;;
  *)
    echo " Usage: $0 {start|stop|restart|status} "
    exit 1

esac
